### PR TITLE
fix #71: fix revert

### LINKED ISSUE #68: get rid of the animation hiding grey borders due to too many usability issues

### LINKED ISSUE #71: fix revert

### PR DESCRIPTION
**Pull request by hchiam**
# Problem/Need:

revert the revert to actually fix #68

# Suggested changes:

# Reminders for @hchiam:

- [ ] `yarn deploy` to update surge site
- [ ] update <https://codepen.io/hchiam/pen/jOBOaqm>

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -595,43 +595,41 @@ function saveHtmlFile(html) {
 }
 
 function animateMove(originJQueryElement, destinationJQueryElement) {
+  destinationJQueryElement.css("visibility", "hidden");
```
Comment (hchiam) [inline index.js:598]: looks like a lot of changes, but actually just removing the outer-wrapping `setTimeout` of 1000 ms

**Review by hchiam — COMMENTED** [review]
LGTM! :+1:
